#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""render_timetable_svg.py

Render a mobile-friendly timetable card as SVG and write to assets/timetable-card.svg.

Input: Timetable.md is generated by scripts/update_timetable_md.py (uses timetable/schedule.py).
This renderer re-runs the timetable queries directly for reliability.

Environment:
- TIMETABLE_DIR: path to timetable repo (same as update_timetable_md.py)
- OUTPUT: optional output path (default: assets/timetable-card.svg)

Design goal:
- Looks good on GitHub mobile
- One-screen card: Today + Week overview (Mon-Sun, show class count)

Note: Keep SVG self-contained (no external fonts/images).
"""

from __future__ import annotations

import os
import html
import subprocess
from datetime import date, datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

TZ = ZoneInfo("Asia/Shanghai")

REPO_ROOT = Path(__file__).resolve().parents[1]
ASSETS_DIR = REPO_ROOT / "assets"
DEFAULT_OUT = ASSETS_DIR / "timetable-card.svg"

# TIMETABLE_DIR resolution (same logic as update_timetable_md.py)
_guess = (Path(__file__).resolve().parents[2] / "timetable")
TIMETABLE_DIR = Path(_guess if _guess.exists() else "/home/ubuntu/.openclaw/workspace/timetable")
TIMETABLE_DIR = Path(os.environ.get("TIMETABLE_DIR", str(TIMETABLE_DIR)))
SCHEDULE_PY = TIMETABLE_DIR / "schedule.py"

WEEKDAY_CN = ["周一", "周二", "周三", "周四", "周五", "周六", "周日"]


def run_query(q: str) -> str:
    p = subprocess.run(
        ["python3", str(SCHEDULE_PY), q],
        cwd=str(TIMETABLE_DIR),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    if p.returncode != 0:
        raise RuntimeError((p.stderr or p.stdout).strip() or f"schedule.py exited {p.returncode}")
    return p.stdout.strip()


def parse_courses(out: str) -> tuple[str, list[tuple[str, str, str]]]:
    lines = out.splitlines()
    header = lines[0] if lines else ""
    courses: list[tuple[str, str, str]] = []
    for ln in lines[1:]:
        ln = ln.strip().lstrip("- ").strip()
        if "｜" in ln:
            parts = [p.strip() for p in ln.split("｜")]
            t = parts[0] if len(parts) > 0 else ""
            n = parts[1] if len(parts) > 1 else ""
            loc = parts[2] if len(parts) > 2 else ""
            courses.append((t, n, loc))
    return header, courses


def esc(s: str) -> str:
    return html.escape(s, quote=False)


def svg_text(x: int, y: int, text: str, size: int = 24, weight: int = 400, fill: str = "#111827") -> str:
    return (
        f'<text x="{x}" y="{y}" fill="{fill}" font-size="{size}" '
        f'font-weight="{weight}" font-family="-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Arial">{esc(text)}</text>'
    )


def main() -> int:
    out_path = Path(os.environ.get("OUTPUT", str(DEFAULT_OUT)))
    ASSETS_DIR.mkdir(parents=True, exist_ok=True)

    now = datetime.now(TZ)
    today = now.date()
    monday = today - timedelta(days=today.weekday())

    # Today details
    out_today = run_query("today")
    header_today, courses_today = parse_courses(out_today)

    # Week overview: counts per day
    day_counts: list[int] = []
    for i in range(7):
        d = monday + timedelta(days=i)
        _h, cs = parse_courses(run_query(d.isoformat()))
        day_counts.append(len(cs))

    # Canvas
    W, H = 1080, 1350
    pad = 56

    # Colors (tech-blue, but subtle)
    bg = "#0b1220"
    card = "#101a2f"
    card2 = "#0f1b33"
    text = "#e5e7eb"
    mut = "#93a4c7"
    accent = "#60a5fa"
    ok = "#34d399"

    y = pad + 54

    parts: list[str] = []
    parts.append(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" viewBox="0 0 {W} {H}">')
    parts.append(f'<rect x="0" y="0" width="{W}" height="{H}" rx="0" fill="{bg}"/>')

    # Main card
    parts.append(f'<rect x="{pad}" y="{pad}" width="{W-2*pad}" height="{H-2*pad}" rx="36" fill="{card}" stroke="#1f2a44"/>')

    parts.append(svg_text(pad + 44, y, "课程表", size=44, weight=700, fill=text))
    parts.append(svg_text(pad + 44, y + 46, f"更新 {now.strftime('%Y-%m-%d %H:%M')}（北京）", size=22, weight=400, fill=mut))

    # Today block
    y += 110
    parts.append(f'<rect x="{pad+32}" y="{y}" width="{W-2*pad-64}" height="420" rx="28" fill="{card2}" stroke="#1f2a44"/>')
    parts.append(svg_text(pad + 64, y + 70, "今日", size=30, weight=700, fill=text))
    parts.append(svg_text(pad + 150, y + 70, header_today, size=22, weight=400, fill=mut))

    if not courses_today:
        parts.append(svg_text(pad + 64, y + 140, "无课", size=32, weight=700, fill=ok))
    else:
        yy = y + 140
        for t, name, loc in courses_today[:5]:
            parts.append(svg_text(pad + 64, yy, f"{t}", size=22, weight=700, fill=accent))
            parts.append(svg_text(pad + 300, yy, name, size=22, weight=600, fill=text))
            parts.append(svg_text(pad + 300, yy + 30, loc, size=20, weight=400, fill=mut))
            yy += 86

    # Week block
    y += 460
    parts.append(f'<rect x="{pad+32}" y="{y}" width="{W-2*pad-64}" height="640" rx="28" fill="{card2}" stroke="#1f2a44"/>')
    parts.append(svg_text(pad + 64, y + 70, "本周概览", size=30, weight=700, fill=text))
    parts.append(svg_text(pad + 220, y + 70, f"{monday.isoformat()} ~ {(monday+timedelta(days=6)).isoformat()}", size=22, weight=400, fill=mut))

    # 7 rows
    row_y = y + 130
    row_h = 72
    for i in range(7):
        d = monday + timedelta(days=i)
        cnt = day_counts[i]
        label = f"{WEEKDAY_CN[i]} {d.strftime('%m-%d')}"
        parts.append(svg_text(pad + 64, row_y + i*row_h + 30, label, size=24, weight=700, fill=text))

        # pills
        pill_w = 140
        pill_h = 40
        px = W - pad - 64 - pill_w
        py = row_y + i*row_h + 4
        fill = ok if cnt > 0 else "#334155"
        parts.append(f'<rect x="{px}" y="{py}" width="{pill_w}" height="{pill_h}" rx="20" fill="{fill}"/>')
        pill_txt = f"{cnt} 节" if cnt > 0 else "无课"
        parts.append(svg_text(px + 38, py + 28, pill_txt, size=20, weight=700, fill="#06111f" if cnt > 0 else text))

        # divider
        if i < 6:
            parts.append(f'<line x1="{pad+64}" y1="{row_y + (i+1)*row_h}" x2="{W-pad-64}" y2="{row_y + (i+1)*row_h}" stroke="#1f2a44"/>')

    parts.append(svg_text(pad + 64, y + 610, "提示：在飞书对我说 ‘今天课表/明天课表/课表 YYYY-MM-DD’", size=20, weight=400, fill=mut))

    parts.append("</svg>")

    out_path.write_text("\n".join(parts), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
